version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - BASE_URL=${BASE_URL}
    networks:
      - traefik-public
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.abiautocenter.rule=Host(`abiautocenter.de`) || Host(`www.abiautocenter.de`)"
      - "traefik.http.routers.abiautocenter.entrypoints=websecure"
      - "traefik.http.routers.abiautocenter.tls=true"
      - "traefik.http.services.abiautocenter.loadbalancer.server.port=3000"
      - "traefik.docker.network=traefik-public"

networks:
  traefik-public:
    external: true