version: '3.8'

services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:87437Kempten+@postgres:5432/abi_db
      - NODE_ENV=production
      - ADMIN_EMAIL=aemaniegmbh@gmail.com
      - ADMIN_PASSWORD=87437Kempten+
      - JWT_SECRET=IhrGeheimesJWTSecret
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=87437Kempten+
      - POSTGRES_DB=abi_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: